#!/usr/bin/env python3
"""export_zh_norm.py — generate src/textfront/zh_tables.hpp from CPUFast sources.

Tables (algorithmic constants, hardcoded in python source):
  kT2sPairs        : char_convert.py traditional->simplified codepoint pairs,
                     sorted by traditional cp for binary search.
  kOpenCpopMap     : opencpop-strict.txt pinyin -> space-split phones; the
                     file is already sorted and unique on the pinyin key.
  kMeasureDict     : quantifier.py measure_dict in dict insertion order
                     (replace_measure iterates the dict and substring-replaces).

Usage: export_zh_norm.py <CPUFast_root> <out_hpp>
"""
import sys, os, struct

def main():
    root, out = sys.argv[1], sys.argv[2]
    cc = os.path.join(root, "text/zh_normalization/char_convert.py")
    ns = {}
    exec(open(cc, encoding="utf-8").read().split('if __name__')[0], ns)
    simp, trad = ns["simplified_charcters"], ns["traditional_characters"]
    assert len(simp) == len(trad)
    # mirror char_convert.py: t2s_dict is built by later-entries-win overwrite
    t2s = {}
    for t, s in zip(trad, simp):
        t2s[t] = s
    pairs = sorted((ord(t), ord(s)) for t, s in t2s.items())

    oc = os.path.join(root, "text/opencpop-strict.txt")
    oc_map = []
    for line in open(oc, encoding="utf-8"):
        line = line.rstrip("\n")
        if not line.strip():
            continue
        key, val = line.split("\t")
        oc_map.append((key, val.split(" ")))

    # must_erhua / not_erhua come from chinese2.py; parse the literals
    # without importing (chinese2 pulls torch at module level)
    c2path = os.path.join(root, "text/chinese2.py")
    c2src = open(c2path, encoding="utf-8").read()
    import ast
    tree = ast.parse(c2src)
    sets = {}
    for node in tree.body:
        if isinstance(node, ast.Assign) and len(node.targets) == 1 and            isinstance(node.targets[0], ast.Name) and            node.targets[0].id in ("must_erhua", "not_erhua"):
            sets[node.targets[0].id] = [e.value for e in node.value.elts]
    ns["must_erhua"] = sets["must_erhua"]
    ns["not_erhua"] = sets["not_erhua"]

    sys.path.insert(0, root)
    from text.zh_normalization.quantifier import measure_dict as md

    def cstr(s):
        out = '"'
        for ch in s:
            if ch == '"': out += '\\"'
            elif ch == '\\': out += '\\\\'
            elif 32 <= ord(ch) < 127: out += ch
            else:
                b = ch.encode("utf-8")
                out += "".join("\\x%02x" % c for c in b)
        return out + '"'

    with open(out, "w", encoding="utf-8") as f:
        f.write("// zh_tables.hpp — GENERATED by tools/export_zh_norm.py, DO NOT EDIT.\n")
        f.write("// Sources: text/zh_normalization/char_convert.py (t2s),\n")
        f.write("//          text/opencpop-strict.txt (pinyin->phones),\n")
        f.write("//          text/zh_normalization/quantifier.py measure_dict.\n#pragma once\n\n#include <cstddef>\n#include <cstdint>\n#include <utility>\n\nnamespace gsv::textfront {\n\n")
        f.write("// traditional -> simplified single codepoint, sorted by .first\n")
        f.write(f"inline const std::pair<uint32_t, uint32_t> kT2sPairs[{len(pairs)}] = {{\n")
        for i in range(0, len(pairs), 8):
            row = ", ".join("{0x%X,0x%X}" % p for p in pairs[i:i+8])
            f.write("    " + row + ",\n")
        f.write("};\n")
        f.write(f"inline constexpr size_t kT2sPairs_len = {len(pairs)};\n\n")
        f.write("// opencpop-strict: pinyin string -> phone list (sorted by key)\n")
        f.write("struct OpenCpopEntry { const char* pinyin; const char* const* phones; size_t n; };\n")
        for idx, (k, ph) in enumerate(oc_map):
            f.write(f"inline const char* const kOcPhones{idx}[] = {{")
            f.write(", ".join(cstr(p) for p in ph))
            f.write("};\n")
        f.write(f"inline const OpenCpopEntry kOpenCpopMap[{len(oc_map)}] = {{\n")
        for idx, (k, ph) in enumerate(oc_map):
            f.write(f"    {{{cstr(k)}, kOcPhones{idx}, {len(ph)}}},\n")
        f.write("};\n")
        f.write(f"inline constexpr size_t kOpenCpopMap_len = {len(oc_map)};\n\n")
        # measure dict in insertion order (py3.7+ dicts keep order)
        f.write("// measure_dict in python dict insertion order\n")
        f.write("inline const std::pair<const char*, const char*> kMeasureDict[] = {\n")
        for k, v in md.items():
            f.write(f"    {{{cstr(k)}, {cstr(v)}}},\n")
        f.write("};\n")
        f.write(f"inline constexpr size_t kMeasureDict_len = sizeof(kMeasureDict) / sizeof(kMeasureDict[0]);\n\n")
        # must_erhua / not_erhua already live in lexicon.hpp (exported with
        # the jieba tables); verify our parse matches them as a sanity check.
        assert len(ns["must_erhua"]) == 8 and len(ns["not_erhua"]) == 44
        f.write("}  // namespace gsv::textfront\n")
    print(f"wrote {out}: {len(pairs)} t2s pairs, {len(oc_map)} opencpop entries, {len(md)} measures")

if __name__ == "__main__":
    main()
