#!/usr/bin/env python3
"""Generate src/textfront/symbols2.hpp from CPUFast text/symbols2.py.

The generated header holds the exact v2 symbol table (732 entries) as a
compile-time constant list plus a compile-time sorted index for id lookup,
mirroring `cleaned_text_to_sequence(version="v2")`.

    GPTSoVits-python tools/export_symbols2.py \
        [--symbols /path/to/CPUFast/GPT_SoVITS/text/symbols2.py] \
        [--out src/textfront/symbols2.hpp]
"""
import argparse
import os


def main():
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    ap = argparse.ArgumentParser()
    ap.add_argument("--symbols",
                    default="/Volumes/2T/GPT-SoVITS-CPUFast/GPT_SoVITS/text/symbols2.py")
    ap.add_argument("--out",
                    default=os.path.join(here, "src", "textfront", "symbols2.hpp"))
    args = ap.parse_args()

    # execute the vendored symbols2.py in isolation (it only defines lists)
    ns = {}
    with open(args.symbols, encoding="utf-8") as f:
        exec(compile(f.read(), args.symbols, "exec"), ns)
    symbols = ns["symbols"]
    assert len(symbols) == len(set(symbols)) == 732, f"unexpected symbol count {len(symbols)}"

    # sorted (symbol, id) pairs for binary search at runtime
    order = sorted(range(len(symbols)), key=lambda i: symbols[i])

    lines = []
    lines.append("// symbols2.hpp — GENERATED by tools/export_symbols2.py, DO NOT EDIT.")
    lines.append("// Source: GPT_SoVITS/text/symbols2.py (v2Pro family, 732 symbols).")
    lines.append("// Mirrors text/__init__.py cleaned_text_to_sequence(version=\"v2\"):")
    lines.append("//   id = index into kSymbols2[]")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <algorithm>")
    lines.append("#include <cstdint>")
    lines.append("#include <string_view>")
    lines.append("")
    lines.append("namespace gsv::textfront {")
    lines.append("")
    lines.append(f"inline constexpr int kSymbols2Count = {len(symbols)};")
    lines.append("")
    lines.append("// symbol strings, indexed by phone id")
    lines.append("inline constexpr const char* kSymbols2[kSymbols2Count] = {")
    for s in symbols:
        esc = s.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    "{esc}",')
    lines.append("};")
    lines.append("")
    lines.append("// ids sorted by symbol string (binary-search index)")
    lines.append("inline constexpr uint16_t kSymbols2SortedById[kSymbols2Count] = {")
    for i in range(0, len(order), 16):
        chunk = ", ".join(str(order[j]) for j in range(i, min(i + 16, len(order))))
        lines.append(f"    {chunk},")
    lines.append("};")
    lines.append("")
    lines.append("// Returns the phone id of `sym`, or -1 when unknown (caller maps")
    lines.append('// unknown phones to "UNK" like clean_text does).')
    lines.append("inline int symbols2Id(std::string_view sym) {")
    lines.append("    int lo = 0, hi = kSymbols2Count;")
    lines.append("    while (lo < hi) {")
    lines.append("        int mid = lo + (hi - lo) / 2;")
    lines.append("        std::string_view s{kSymbols2[kSymbols2SortedById[mid]]};")
    lines.append("        if (s < sym) lo = mid + 1;")
    lines.append("        else if (s > sym) hi = mid;")
    lines.append("        else return static_cast<int>(kSymbols2SortedById[mid]);")
    lines.append("    }")
    lines.append("    return -1;")
    lines.append("}")
    lines.append("")
    lines.append("}  // namespace gsv::textfront")
    lines.append("")

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote {args.out}: {len(symbols)} symbols")


if __name__ == "__main__":
    main()
